### PR TITLE
Some improvements

### PR DESCRIPTION
**Pull request by christian-bromann**
Hey,

I wanted to use the concise reporter but it seems it doesn't quite work the way I expected: I don't know how you have to pass in your capabilities in order to display them. I got something like

```
 ========= Your concise report ==========
chrome::undefined:undefined::undefined:undefined::undefined
```

I tweaked the reporter so it uses the right capability properties. I also only print them out when available (local vs remote testing). At the end I got rid of the build files which don't need to be versioned.

### CODE REVIEW

**Comment by FloValence** [comment]
Hello Christian,

Thank you for your pull-request.
For the capabilities those I used are BrowserStack specific capabilities : [BrowserStack Capabilities](https://www.browserstack.com/automate/capabilities)

May be we can work around to keep compatibility with the two types of capabilities ?
What do you think ?

For the other two commits, they are very welcome :-)

**Comment by christian-bromann** [comment]
Oh didn't know that BrowserStack manages its own capability keys 🙈 . According to the [Webdriver protocol](https://w3c.github.io/webdriver/webdriver-spec.html#capabilities) these are not valid. Let me implement a helper method that merges these caps together.

**Comment by FloValence** [comment]
Just let me know when you're ok :)

**Review by FloValence — CHANGES_REQUESTED** [review]
Implement a helper method to keep BrowserStack capabilities

**Comment by christian-bromann** [comment]
@FloValence how about that?

**Review by FloValence — APPROVED** [review]

**Comment by FloValence** [comment]
Seems good for me!
Thank you for your contribution :)

**Pull request merged**
